### ISSUE TITLE
Nothing placed on clipboard-Firefox 58/Windows 10

### ISSUE THREAD

**Issue by peteypoo** [fwenzel/copy-shorturl#89] opened 2018-02-09 16:23 UTC
Clicking the tool bar icon pops up the notification, but the clipboard still contains the old value that was placed there previously.

Is it possibly a Firefox setting?

**Comment by fwenzel** [comment] 2018-02-10 20:23
Oh this is interesting, thank you for pointing it out. I do not have Windows 10, so it will be hard for me to reproduce if it only happens on Win :-/

**Comment by fwenzel** [comment] 2018-02-19 00:09
What page is this happening on? Anything suspicious in the JavaScript console?

**Comment by peteypoo** [comment] 2018-02-19 02:39
This happens on all pages.  JavaScript console shows nothing.
Sorry to leave you, but I've taken my business to one of your 'competitors' :-)

Good luck!

**Comment by fwenzel** [comment] 2018-02-24 20:49
lol, whatever works for you. I'll double-check that the add-on still works as expected for everyone else.

**Comment by xh6ynr21y** [comment] 2018-04-14 17:26
this issue happens to me on macos high sierra 10.13.4 and firefox 59.0.2.
it works neither with the keyboard shortcut (cmd+shift+l), not the right click context menu.

any idea?

**Comment by y0y0z** [comment] 2018-04-20 11:33
anyone??

**Comment by fwenzel** [comment] 2018-04-22 05:05
I'll double check what's happening. Sometimes Firefox APIs change and add-ons silently break without the developer noticing. Ugh.

**Comment by fwenzel** [comment] 2018-07-14 17:04
Unfortunately I still cannot reproduce this issue, and I do not have Windows 10 to test further with :-/

**Comment by fwenzel** [comment] 2018-07-14 17:11
I'll see if I can reproduce this on an instance of https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by fwenzel** [comment] 2018-10-13 19:10
I was unable to reproduce this on Windows.

**Comment by invalidbeard** [comment] 2018-11-28 15:40
I'm having this issue now. Windows 7 Ultimate 64 bit.

**Comment by fwenzel** [comment] 2019-05-26 22:07
Closing this for now, since it seems impossible to reproduce. Please reopen if you can help narrow this down thank you :)

**Closed by fwenzel** 2019-05-26 22:07 UTC
