### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by zambala** [fwenzel/copy-shorturl#131] opened 2022-01-30 14:04 UTC
I installed the extension, then set the service.....

No Results whatever, it doesn't show up in mouse rightclick, neither when I click the extension button nothing happens at all; I can't see what else I should do...

Using Firefox Developer 72.0b9 , desktop

**Comment by fwenzel** [comment] 2022-01-30 18:29
Do you see anything in the browser console? (Ctrl+Shift+J)

If the extension has an error you should be able to see something there.

**Comment by fwenzel** [comment] 2022-01-30 18:30
Also what page are you using this on? Try on google.com, to make sure there's no bug with the specific page you want.

**Comment by fwenzel** [comment] 2022-05-23 20:55
Closing this out for now, since I cannot reproduce the issue - but please reopen with steps to reproduce if you can.

**Closed by fwenzel** 2022-05-23 20:55 UTC
